// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fique_conectado_backend.Context;

#nullable disable

namespace fique_conectado_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240819124538_AtualizacaoCadastro")]
    partial class AtualizacaoCadastro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("fique_conectado_backend.Models.Entertainment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathPoster")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Release")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("entertainment", (string)null);
                });

            modelBuilder.Entity("fique_conectado_backend.Models.List", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("list", (string)null);
                });

            modelBuilder.Entity("fique_conectado_backend.Models.ListEntertainment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntertainmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntertainmentId1")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ListId")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("EntertainmentId1");

                    b.HasIndex("ListId");

                    b.ToTable("listEntertainments", (string)null);
                });

            modelBuilder.Entity("fique_conectado_backend.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntertainmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntertainmentId1")
                        .HasColumnType("TEXT");

                    b.Property<float>("NumRating")
                        .HasColumnType("REAL");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntertainmentId1");

                    b.HasIndex("UserId");

                    b.ToTable("rating", (string)null);
                });

            modelBuilder.Entity("fique_conectado_backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("fique_conectado_backend.Models.List", b =>
                {
                    b.HasOne("fique_conectado_backend.Models.User", null)
                        .WithMany("Lists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("fique_conectado_backend.Models.ListEntertainment", b =>
                {
                    b.HasOne("fique_conectado_backend.Models.Entertainment", null)
                        .WithMany("ListEntertainments")
                        .HasForeignKey("EntertainmentId1");

                    b.HasOne("fique_conectado_backend.Models.List", null)
                        .WithMany("ListEntertainments")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("fique_conectado_backend.Models.Rating", b =>
                {
                    b.HasOne("fique_conectado_backend.Models.Entertainment", null)
                        .WithMany("Ratings")
                        .HasForeignKey("EntertainmentId1");

                    b.HasOne("fique_conectado_backend.Models.User", null)
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("fique_conectado_backend.Models.Entertainment", b =>
                {
                    b.Navigation("ListEntertainments");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("fique_conectado_backend.Models.List", b =>
                {
                    b.Navigation("ListEntertainments");
                });

            modelBuilder.Entity("fique_conectado_backend.Models.User", b =>
                {
                    b.Navigation("Lists");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
